### ISSUE TITLE
Memory leak in list.create()/list.append()

### ISSUE THREAD

**Issue by vipo** [aerospike/aerospike-server#118]
We are facing a very strange behavior in our production system (which uses ssd disks) and we cannot reproduce the situation with in-memory namespaces in our dev environment. Aerospike process leaks memory (a few gigs per hour) and eventually is killed by oom killer. Consumed memory is not reported to AMC.

Such memory leak appears if we have such scenario in lua udf:
1) local l = list.create(N)
2) list.append(l, some_value)
AND step 2 is executed more than N times

If N is big enough (i.e. list.append is called less times then N) than we do not see any memory leakage.

Any ideas why this happens? Is it a bug, is it an intended behavior?

Thanks.

**Comment by bwhisler** [comment]
I'm not sure why this is happening, but it is not the intended behavior.  What version of the server are you using?  Also, what is the return value of the Lua function -- is it returning the list?

Thanks.

**Comment by vipo** [comment]
Version: 3.6.3

We do not return anything from udf.

Thanks.

**Comment by bwhisler** [comment]
It's possible that your production machines are suffering from memory fragmentation due to the lists being repeatedly reallocated as they grow, which can result in the behavior you're seeing.

One way to reduce reallocations is simply to increase the initial size of the list -- as you've seen, when N is large enough that the list never needs to be reallocated, there are no problems.

Also, I'd suggest using a second parameter to list.create() to specify a large capacity step size, which is the amount by which the list grows (via reallocation) whenever it must be expanded.  By default, this value is 10, so that the list must be reallocated after every 10 insertions once it has grown beyond its initial size.  This can be very inefficient if the lists are large.  You might try list.create(N, 1000) or whatever seems logical for the typical size of your lists.

I hope this helps!

**Comment by vipo** [comment]
Thank you!
