### ISSUE TITLE
Implement user-defined key hashing

### ISSUE THREAD

**Issue by ddorian** [aerospike/aerospike-server#136]
Meaning, the user is smart enough to send multiple keys to 1 server (when they are all from 1 user) so he can make complex queries/functions on keys that are guaranteed to be located in 1 server. The ~nicest way this is done is like redis does it.

**Comment by ddorian** [comment]
Any comment ? This way you can also implement bulk inserts/updates/deletes as long as they point to 1 node.

**Comment by bbulkow** [comment]
You can actually do this in some aerospike clients. There is the ability to set and get by digest. Digests of a certain range are guarenteed to be on the same server - there are 4k partitions, so manufacture your digest carefully, and make sure you avoid collisions. You can't use the standard get and set functions after that point ( which take a key and generate a digest ). Look at the functions that are "by_digest". If you read the Aerospike code, you can see how we use the digest internally to decide which data is on which partition, and one which device within a server.

Bulk operations are a different problem from application-managed locality. Bulk operations split into a separate operation for each server, each of which happens in parallel. That way, when you scale up your cluster, it goes faster. Our batch operations, query operations, etc do that for you ( and writes and deletes, which we have implemented for long-haul replication but not yet exposed in clients ). In fact, for large bulk operations, you are better off having data on different servers because then when you grow the cluster you have more nodes participating. Placement is a win only when you have two or three small items - and if there's a natural grouping, put them as different bins in the same record.

Managing placement is a different thing from being able to do bulk operations.

It's likely that you don't want to manage locality yourself. Unless you are very clever, you'll end up with hot partitions, hot data, and poor distribution  - and the person who takes over maintaining your app must be just as clever as you. The point of using digests and hash functions is to get very, very random distribution - allowing seamless scale-out - and it's a powerful idea.

At Aerospike, we limit your network hop to exactly one network hop. That's a predictable and reasonable price to pay, we think. If you disagree, enjoy the digest functions.

**Comment by ddorian** [comment]
Only aerospike + couchbase don't offer a way to define the partition/shard key. 
While I know it may/will cause hotspots, many features can't be done AT ALL without partitioning many rows together (easier to make complex queries that won't hit all servers when you can partition by "user_id" or similar).

You can also maybe offer transactions like redis does if all operations are in 1 partition.

I'll check the "by_digest" operations out.

Thanks
