### ISSUE TITLE
xdr_uptime metric reports timestamp, not duration

### ISSUE THREAD

**Issue by RonRothman** [aerospike/aerospike-server#146]
The `xdr_uptime` metric is reporting a unix timestamp (seconds since epoch), not a duration (seconds up) [as per the documentation](http://www.aerospike.com/docs/reference/metrics#xdr_uptime).

```
$ asinfo -v version
Aerospike Enterprise Edition build 3.9.0.2
$ asinfo -v statistics | sed -e 's/;/\n/g' | grep uptime
uptime=43909
xdr_uptime=1469634903
```

**Comment by sud82** [comment]
Hi RonRothman,
You are getting unix timestamp because your XDR is disable in config file.
XDR uptime is (currentTime - BootTime), when XDR is disable then we would get just currentTime. We should have added this check but unfortunately we missed. As even in disabled condition, this uptime could confuse someone.
In future Aerospike versions we are removing this uptime info, because XDR and ASD are now no different processes. So uptime for both of them would be same.

**Comment by wchu-citrusleaf** [comment]
removed in 3.11.1
