### ISSUE TITLE
aerospike server 

### ISSUE THREAD

**Issue by thomas-activevideo** [aerospike/aerospike-server#157]
Hi, 
We use our own configuration file /etc/aerospike/aerospike.conf which stipulates to start the Aerospike server (asd) with a specific user, **thomas** in the example below. 

```
service {
    user thomas
    group thomas

    paxos-single-replica-limit 1   

    service-threads 16              
    transaction-queues 16            
    transaction-threads-per-queue 4
    proto-fd-max 15000
}

logging {
    console {
        context any info
    }
}
```

When we run under CentOS 7.2, Aerospike Server Community with version 3.8.4, the service is started as follows:
```
systemctl start aerospike
```
The process is then started as **root** and not as the username/group **thomas** specified in the configuration file.

Could you let us know whether this is a known issue. Is there a way to work around?

**Comment by dandric-activevideo** [comment]
Note, aerospike runs as `root` due to commit 921764d, but even before that, the user was still hardcoded to `aerospike` in the `aerospike.service` file.

**Comment by psi-mankoski** [comment]
We follow the standard systemd way of using the unit file ("/usr/lib/systemd/system/aerospike.service") to set the default user and group, which can be overridden via the drop-in file "/etc/systemd/system/aerospike.service.d/aerospike.conf", e.g., 

Prompt$ cat /etc/systemd/system/aerospike.service.d/aerospike.conf
[Service]
User=aerospike
Group=aerospike
Prompt$

One note of caution: The "/usr/bin/asd-coldstart" helper script does its work by manipulating that drop-in file, so you should make corresponding modifications to the other 2 files in that directory ("aerospike.conf.default" and "aerospike.conf.coldstart") if you change "aerospike.conf" so that the desired settings are used and not lost when cold-starting.

**Comment by djc** [comment]
This makes the user/group specified in `/etc/aerospike/aerospike.conf` confusing at best. Are there plans to remove it from that configuration file?

**Comment by psi-mankoski** [comment]
The basic `aerospike.conf` supplied with the Aerospike Server package on distros supporting systemd omits those lines (and they're ignored if present but not prohibited), which are necessary as options in SysV Init-based distros (and so those lines are included in the conf. files for those packages.)

I agree it's potentially confusing, but we need to keep it this way to support the server's daemonization option, which manifests differently on systemd vs SysV Init-based distros.
