### ISSUE TITLE
No cursor no pagination?

### ISSUE THREAD

**Issue by arganzheng** [aerospike/aerospike-server#178]
Aerospike seems not have cursor or pagination support? How to do something like "limit/offset" in Aerospike?

**Comment by wchu-citrusleaf** [comment]
Correct. This currently is not a functionality that is supported in Aerospike.

**Comment by arganzheng** [comment]
Any schedule for this functionality?

**Comment by bbulkow** [comment]
The short answer is no. There are many features of modern systems that make cursors low priority ( not zero, mind you, but low ).

1. Modern "client" machines are big. Aerospike is usually fronted by a web app or REST service, and the pagination between a small client will be done there. Those servers are "big", ie, have 64G and 128G of RAM. Since the work of pagination - holding a buffer - must be done somewhere, doing it in those machines makes more sense than doing it in the database and slowing down all other users.

2. TCP backpressure and asynchronous operations work well. If you look at how you scan a larger Aerospike database, we have a TCP connection that stays open a long time. That TCP connection provides a very accurate flow control which is push based. As soon as enough buffer is in the receiver's kernel, the window opens, the connection becomes writable, and we read more rows to fill it. For really big queries, this is more efficient, especially when tied to an async processing framework so the client is notified when more data is available.

3. Large requests, larger than fits in a client's memory ( ie, multi-GB ), are not the core use case of Aerospike - nor, I might argue, most databases. It is more effective to use Predicate Filters, to use Indexes, to use smaller objects ( a 1MB or even 8MB object fits in a single request every time ), to use a large number of small objects with higher selectivity, to use Aggregations, than to try to push multiple GB over the network and have the client process it. We are making progress and have features scheduled for that - such as the Predicate Filter work that came out in 3.12, so you don't have as much need for cursors.

If you could explain in more detail why these three ideas don't fit your use case, I'd be happy to have a dialog. You can reach me at brian@aerospike.com .
