### ISSUE TITLE
can not start aerospike in centos 6.3, no version information available (required by bin/asd)

### ISSUE THREAD

**Issue by arganzheng** [aerospike/aerospike-server#182]
Has any body encounter this problem?
OS Version: CentOS release 6.3 (Final)
Aerospike version： Community Edition 3.12.1
Error Message:

```
# bin/aerospike start
error: start failed due to an error.
/home/work/aerospike-server/bin/asd: /lib64/libz.so.1: no version information available (required by /home/work/aerospike-server/bin/asd)
/home/work/aerospike-server/bin/asd: /usr/lib64/libcrypto.so.1.0.0: no version information available (required by /home/work/aerospike-server/bin/asd)
Apr 07 2017 04:03:02 GMT: WARNING (cf:misc): (hardware.c:626) no NUMA information found in /sys

```

**Comment by tlopatic** [comment]
Thanks for reporting this. Could you provide the parts of your aerospike.log file that show the attempt to start the Aerospike server?

I am asking, because none of the above messages necessarily causes Aerospike startup to fail. I'm hoping that we will find more information about the startup failure in /var/log/aerospike.log.

About the above error messages:

- The "no version information available" message likely means that Aerospike expects newer versions of the shared libraries libz.so (RPM package "zlib") and libcrypt.so (RPM package "openssl") on your system. Can you share the versions of these two installed RPM packages on your system?

- The "NUMA information" means that a few pieces of information about the system's hardware are missing from the /sys file system. Is this a virtual machine by any chance? In any case, this shouldn't prevent Aerospike from starting.

**Comment by arganzheng** [comment]
hi tlopatic, thanks for you quick response.

We struggle for this problem from yesterday, and try all the way we can think of without luck. And just now, it run out with the same error message, we did not do anything different, just reinstall it from scratch..

**Comment by tlopatic** [comment]
Great! Thank you for reporting back! I'm glad to hear that the issue is resolved.

Have a good weekend!

**Comment by wchu-citrusleaf** [comment]
@arganzheng most likely aerospike was not started because of the system library mismatch. Your reinstallation probably resolved the mismatch.
