### ISSUE TITLE
Segfault on server start (BPIM64)

### ISSUE THREAD

**Issue by StephaneRenouard** [aerospike/aerospike-server#187]
try to compile on BPI M64 (Arm A64) from github source (main branch).  GCC version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4). 

Compile OK, but I had a seg fault at launch when make start:

> ...
May 31 2017 08:17:15 GMT: INFO (paxos): (paxos.c:3741) starting paxos threads
May 31 2017 08:17:15 GMT: INFO (nsup): (thr_nsup.c:1421) starting namespace supervisor threads
May 31 2017 08:17:15 GMT: INFO (demarshal): (thr_demarshal.c:863) starting 4 demarshal threads
May 31 2017 08:17:15 GMT: INFO (demarshal): (socket.c:709) Started client endpoint 0.0.0.0:3000
May 31 2017 08:17:15 GMT: INFO (info-port): (thr_info_port.c:307) starting info port thread
May 31 2017 08:17:15 GMT: INFO (info-port): (socket.c:709) Started info endpoint 0.0.0.0:3003
May 31 2017 08:17:15 GMT: INFO (as): (as.c:453) service ready: soon there will be cake!
May 31 2017 08:17:15 GMT: WARNING (as): (signal.c:181) SIGSEGV received, aborting Aerospike Community Edition build 3.12.1.1 os ubuntu16.04
May 31 2017 08:17:15 GMT: WARNING (as): (signal.c:185) stacktrace: found 1 frames
May 31 2017 08:17:15 GMT: WARNING (as): (signal.c:185) stacktrace: frame 0: ./target/Linux-aarch64/bin/asd(as_sig_handle_segv+0x58) [0x48caa8]
Makefile:88: recipe for target 'start' failed
make: *** [start] Segmentation fault

Do you have any clues  ?

**Comment by bcarld** [comment]
I have been working on getting aerospike to run on ppc64le and also run into this problem.
I found the issue on 7/4 to be that `cf/include/socket.h` defines `struct cf_poll_event` to be PACKED. This conflicts with the definition of  `struct epoll_event` in `/usr/include/linux/eventpoll.h` which only applies the PACKED attribute if `__X86_64__` is defined at compile time.
This mismatched packing of the structure leads to the Aerospike code reading the data pointer 4 bytes off of the address at which the pointer is stored -- thus getting an invalid pointer which leads to the sigsegv.

I have a patch that I was looking to submit.  But we have another compilation issue where Intel intrinsic functions are used to prefetch some data. These functions are used without any architecture protection and since they are not available on PPC64, the compile fails.
I was just beginning to see what could be done about these 2 issues (fix them together, or separately).
Given that there is already an issue on the sigsegv, I am now leaning toward separating the fixes.

**Comment by psi-mankoski** [comment]
Thank you both for the input. We aim to have portable code within the scope of our mandate to ensure the Aerospike Server codebase works correctly, runs efficiently, and is maintainable on a short list of key Linux server distros (found in the top-level README) on x86_64.

We would be glad to review any pull requests you may submit, but please understand that if portability to additional systems requires, e.g., too many #ifdef's, we wouldn't be able to accept them. That being said, it seems the basic changes you mentioned might be possible without major diffs.

Good luck!
