### ISSUE TITLE
[FreeBSD support] Please consider replacing Linux-specific code with POSIX code

### ISSUE THREAD

**Issue by yurivict** [aerospike/aerospike-server#23]
I get this failure on FreeBSD:
```
cf_mutex.c:30:10: fatal error: 'linux/futex.h' file not found
#include <linux/futex.h>
         ^~~~~~~~~~~~~~~
```

This makes the project Linux-specific.

**Comment by kportertx** [comment]
> I get this failure on FreeBSD

Currently, Aerospike is only supported on Linux.

**Comment by akshatakanihal** [comment]
@yurivict I would like to work on this issue. could you please give me permission to work on this issue?

**Comment by yurivict** [comment]
@akshatakanihal Sure, you have permission.

**Comment by akshatakanihal** [comment]
Thank you.

**Comment by kportertx** [comment]
I'm not sure who the person providing permission is. There is a contributor's agreement that we would ask you to fill out before we could accept any pull requests.

That said, futex isn't the only linux specific code in the server. Hardware.c reads from proc and sys. Fabric, service, and heartbeat use epoll, I wouldn't be surprised if there are others. We haven't had much demand for other OSes so supporting BSD and effectively doubling our QE testing hasn't made sense financially.

That said, the reason we use futex rather than pthread locks is that the futex locks are 4 bytes while the pthread locks are 40 bytes. This 10x memory savings had been put to good use in many places that would be too expensive with the pthead locks. Maybe there are 4 byte alternatives, but we haven't really looked for the reason mentioned above.
