### ISSUE TITLE
Calling a global function from another global function in the same file gives an error. 

### ISSUE THREAD

**Issue by sacheendra** [aerospike/aerospike-server#37]
The error is like this. 
attempt to call global 'function name' (a nil value)
The function is defined in a line before it is called. 

A way of solving this problem is first executing the script once and then calling function from that script. 
Is this done in aerospike? If it is why does calling the function return an error? 

Reference: http://lua-users.org/lists/lua-l/2011-01/msg01154.html

**Comment by psi-mankoski** [comment]
Thanks for the issue report. We are looking into this. Is the only problem that the function does not get called, or do you see other problematic behavior?
Thanks!

\*\*\*PSI***<BR><<<<psi@aerospike.com>>>>

**Comment by sacheendra** [comment]
The only problem is that the function does not get called. 
I have observed problems if a global and a local function in the file have the same name and opened another issue regarding it. #38

**Comment by psi-mankoski** [comment]
Sacheendra --
Turns out directly calling global scope functions is not supported within Aerospike. Please see our documentation on Lua restrictions: https://www.aerospike.com/docs/udf/getting_started.html#lua-restrictions
If a global function is put into a local variable (or called from / returned by a local function), however, it can be invoked via the local variable (or local function or local function return value) by any function in that same module.
