### ISSUE TITLE
Porting PPC64LE 

### ISSUE THREAD

**Issue by pranavpandit1** [aerospike/aerospike-server#48]
Hello,

I am trying to port aerospike to ppc64le, with that currently I can see there was an existing attempt already made #11 for the same.
Just wanted to understand, if there is any specific reason that the request is still open and without any reviews?
Before starting to put efforts, want to understand beforehand if there are any limitations in this?

Thank you.

**Comment by kportertx** [comment]
There were discussions between the team attempting the port and our team. The changes in #11 were only enough for the server to start, but would crash if you attempted to connect it to a cluster etc.

Now that we have ported to AARCH64, I suspect this porting to PPC64LE will be less difficult. To my knowledge, there hasn't been any demand from PPC, so this hasn't been a priority.

Our non-x86 builds are currently tied to GCC since we wrote a GCC plugin to assist with the porting effort called "[TSO](https://github.com/aerospike/aerospike-server/tree/master/tso)" for "Total Store Order". This plugin inserts memory barriers around certain memory accesses to get the TSO ordering from x86 on other platforms. We manually ported certain\performance critical code paths to the looser memory model and added those files to the [exclude](https://github.com/aerospike/aerospike-server/blob/master/tso/exclude_ce.txt) file (which lists files/functions that the TSO plugin will exclude).
