### ISSUE TITLE
limitations on bins, records, sets

### ISSUE THREAD

**Issue by catroot** [aerospike/aerospike-server#54]
I have tried to fill one million random generated bins named with random data...
Similar like this ('bar', 'demo', 'LWbiaRHR') with one row data (example): 
{ 'LWbiaRHR' : 'yLRMdnZcCVPfnqYKjNftFLdV'}

Everythings works till insert № 16647 of random bin and throws an error:
error: (21L, 'AEROSPIKE_ERR_BIN_NAME', 'src/main/aerospike/as_command.c', 485)
ttl was set to 180 for rows, and even after expiring data error was still there.
Only restart aerospike let me make some inserts and repeats above errors.

**Comment by mtendjou** [comment]
This error should trigger if you sent a bin name that is too long (limit is 14 bytes), if you tried to insert double bytes characters or if you exceeded the namespace's bin name quota (32,767 different bin names allowed maximum). 

Maybe you already had

**Comment by bbulkow** [comment]
This error specifically is happening because you are adding too many bins (although as mtendjou says it also can happen with too long a bin name).

Aerospike is not designed like Cassandra to support an arbitrary number of bins.  We use a stringpool internally to limit the amount of ram used.

Instead, design this shape of your data with one bin, and with either a list or map or LLIST. All of those structures allow arbitrary and unlimited names of data inside the record. They can also be used to select date ranges, which is the pattern you'd use multiple columns for in cassandra --- use a single LLIST with the timestamp as the ordered list element.

This is one reason Aerospike is efficient for some operations - accessing a particular bin does not allow arbitrary names, but instead we have these List Map LLIST which are arbitrary, but there is a "fast path" if you want to elevate some strings, blobs, integers etc as bins.

You can also think of a bin like a single document in Mongo. That can be of arbitrary shape and size (limited to 1M currently by default, unless you use LLIST which allows truely arbitrary size). Bins also contain indexing information, like a relational database.

Hopefully this helps you understand Aerospike's data model and allows you to use it more effectively.

**Comment by catroot** [comment]
I`ve got, that there is a limited number of bins allowed and inside bin a limited number of keys allowed.
So, where to store my million records? inside of a single key? But bin size is also limited. And how to query them? 
Can you give an example using lmap and llist in python?
For now, it looks a way complex for such trivial things.

**Comment by bbulkow** [comment]
Aerospike is like a key value store.

You have a million records.... make them each a record, with their own key, store the value in a bin called whatever you want ("value").

or, if you need to query on key or value, still use the key as "key" create one bin called "key" and one bin called "value" ( or something more descriptive for your dataset). Create indexes of whatever type on each column. Just like a relational model - but one query (get by key) will go very fast, query will go pretty fast but not the same.

If you have a million records _per key_ (don't use just one row in the entire database!), you need LLIST, which is an ordered list like Cassandra as I said. I'm sorry that I can't see an example of the python client LLIST code (I will add a request for this), but the python client has support for LLIST since 1.0.37 . Your best effort might be to look at the Java example code in https://github.com/aerospike/aerospike-client-java/blob/master/examples/src/com/aerospike/examples/LargeList.java and I'm sorry to suggest looking at java code.

**Comment by catroot** [comment]
How many sets can i have in a namespace?
I have a bad feeling that i hit another part of invisible fence (at last for me)
On count 1019 of created sets i`ve got error
error: (4L, 'AEROSPIKE_ERR_REQUEST_INVALID', 'src/main/aerospike/as_command.c', 485)

**Comment by bbulkow** [comment]
Sets are like tables. There are limitations to the number of tables in any database. Why do you need thousands of tables?

**Comment by catroot** [comment]
i`m just trying to find a place where i can store my millions of records.
And there are no place to do that.
Sets quantity is limited, key quantity are limited, bins are limited too..
Every place contain a some sort of limit.

**Comment by bbulkow** [comment]
Why do you say key qunatity is limited? Users have billions and billions of
keys.

**Comment by catroot** [comment]
I just have tried to store my millon random keys..
Cant remember why it fails at my last try... seems to be my mistake..
For now it works! Keys are stored!  Speed around 2k keys per second on my atom 1.6GHz box.
Aerospike took around 30% of cpu time during inserts. 
Bulk insert must be a way faster.

**Comment by bbulkow** [comment]
atom is very very slow. they are very bad for interrupts.  i cant suggest
whether your numbers are well tuned. but it might be right. we are running
on intel nucs for portable clusters and seeing 100k per server.

sent from my phone, please excuse any terseness

**Comment by catroot** [comment]
I`ve got why million keys try falls
It`s falls because of i used different (also radomly generated) bin names.
There a limit for bin names of 32768 for a entire namespace scope, but not per set scope, as i mention.
So, my data looks like
(('bar', 'demo', u'mZvZILAs', bytearray(b'\xff/},^\x8e\x13-\x19\x1eY\xed\x05\xdc?\xba\xc7S|\x8d')), {'mZvZILAs': u'RvhXhzLQcXBfneIHRqwpXQtPuxLGFbYsQuxDnhrZTNrahGinAUTVWSFLyJpEvjwa'})

**Comment by bbulkow** [comment]
Thanks for following up. Yes, the bin name (column name) is not intended to
be used as data :-).

**Comment by catroot** [comment]
Very nice. I promise not to use bin names in that way. ;)
The question is why i didn`t get back to available state a bin names after deleting it. Is the full (or even several times)  aerospike restart needed for this by design or it`s a bug?

**Comment by wchu-citrusleaf** [comment]
This is by design. For look-up performance reasons, the binname strings are kept in a lockless data-structure, which makes safe deletes very hard. 

However, we do understand some of the practical limitations this brings to some users, so will continue to explore alternatives.

**Comment by catroot** [comment]
With column names i didn`t get the point...
From the data sample, mentioned above:
--------------
{'mZvZILAs': u'RvhXhzLQcXBfneIHRqwpXQtPuxLGFbYsQuxDnhrZTNrahGinAUTVWSFLyJpEvjwa'})
mZvZILAs is the column name?
or 
(('bar', 'demo', u'mZvZILAs', bytearray(b'\xff/},^\x8e\x13-\x19\x1eY\xed\x05\xdc?\xba\xc7S|\x8d')), 
mZvZILAs in this place is the column name?
--------------
i imagine that the column name is the first one case, and in second sample `mZvZILAs` is the primary index key.
Fix me if i`m wrong.

**Comment by wchu-citrusleaf** [comment]
This is correct. The column names is the one with the limitation.
