### ISSUE TITLE
questions about ssd configuration

### ISSUE THREAD

**Issue by billbargens** [aerospike/aerospike-server#75]
The configuration mentioned in the official documents for ssd storage is as follows (just call it the raw-device way):

        storage-engine device {
                device /dev/sdc1   #raw device, sdc1 is my ssd disk
                ......
        }
You know for the HDD disk, we can just use it as a file(just call it the file way). When using a file, we need to specify the path of the file and the file size.
So, I make an experiment to use ssd in the so called file way in spite I can find nothing about this way in official documments or in the community:

        storage-engine device {
                file /disk3/jijw/data/aerospike.data  # disk3 is a ssd disk
                filesize 64G
                ......
        }
First, it works. 
And second, the performance looks good, 3.5w read tps. When using the raw-device way, it is about 7.8w.
So, What the difference will be between the two way(raw-device way and file way) in-depth when using ssd?

**Comment by bbulkow** [comment]
Bill,
In raw device mode, Linux removes two very big layers.
- the file system
- the block cache

The file system is a huge layer. Block allocation, metadata update, all kinds of things. You will also find performance differences in different file systems that you might choose, and different effects as the file system gets full.

The block cache is a lighter weight layer, and Linus will tell you it is very fast, but in our testing it adds rather importantly to the latency distribution.

Removing the file layer is a common optimization for databases. With oracle, for example, you use raw devices or files, and with raw devices it is much faster.

Finally, the real issue is measurable difference. 3.5k vs 7.8k is actually not that great. Aerospike often achieves 50k++ TPS on a single drive, we have even achieved 1,000,000TPS (1,000k :-) on intel's recent commodity drives - all the way through flash - so I suggest the performance you're measuring is only the beginning.

I looked around for some explanations about OS file system and page cache and virtual memory architectures, and found this, which might be explanatory, but searching on the topics of Linux OS internals will find you more:
http://duartes.org/gustavo/blog/post/page-cache-the-affair-between-memory-and-files/

You can see that the work the OS does to get IO mapped nicely into memory, and manage virtual memory, is a lot of complexity. Direct IO, by comparison, simply does a command to the disk driver and gets the result. Hopefully that gives you a flavor of the issues involved.

**Comment by gmenegatti** [comment]
@bbulkow thanks for the detailed explanation. Please, is there any Aerospike source code documentation explaining or detailing in more details how you guys handle this raw device access?
I believe I was able to identify some of the source code files [1] where all the process takes place, but some documentation would be really helpful. 
[1] https://github.com/aerospike/aerospike-server/blob/9a80dee49517ef8a24d6b3b72b746a48bab08f33/as/include/storage/drv_ssd.h
https://github.com/aerospike/aerospike-server/blob/68fd9dc13b4738dc9deb00961caefea3a45d85a6/as/src/storage/drv_ssd.c
Happy Aerospike Enterprise customer here. :-)

**Comment by bbulkow** [comment]
Hello Gabriel,
Yes, you've identified the correct files, and the documentation that exists is in the files themselves. I believe you'll find them exploratory - there's a lot more documentation and comments in there than I see in most open source projects. 

If you need more help regarding any aspect of how the product operates, or additions we can make, please reach out through your enterprise support contacts - we're happy to help.

**Comment by gmenegatti** [comment]
Thanks so much @bbulkow
